// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightThemeBlack from 'starlight-theme-black';
import starlightSiteGraph from 'starlight-site-graph';
import starlightLinksValidator from 'starlight-links-validator';

// The ten pillars. Order here is the order in the sidebar; `color` is the graph
// node colour, following the plugin's red -> purple ramp in sidebar order.
// nodeColor1..9 are the only numbered slots, so the tenth pillar takes
// `nodeColorExternal` — a slot nothing else can claim, because external nodes
// only exist when `includeExternalLinks` is on, and it is off. Its value is
// redefined in src/styles/custom.css to continue the ramp into magenta.
const pillars = [
	{ label: 'Threat Intelligence', dir: 'threat-intel', color: 'nodeColor1' },
	{ label: 'Identity & Access Management', dir: 'iam', color: 'nodeColor2' },
	{ label: 'Application Security', dir: 'appsec', color: 'nodeColor3' },
	{ label: 'Governance, Risk & Compliance', dir: 'grc', color: 'nodeColor4' },
	{ label: 'Penetration Testing & Red Teaming', dir: 'pentest', color: 'nodeColor5' },
	{ label: 'AI & Automation Engineering', dir: 'ai-automation', color: 'nodeColor6' },
	{ label: 'Detection Engineering & SecOps', dir: 'detection-eng', color: 'nodeColor7' },
	{ label: 'Cloud & Infrastructure Security', dir: 'cloud-infra', color: 'nodeColor8' },
	{ label: 'Incident Response & Digital Forensics', dir: 'dfir', color: 'nodeColor9' },
	{ label: 'Data Security & Privacy Engineering', dir: 'data-privacy', color: 'nodeColorExternal' },
];

// Deploy target. Defaults to the custom domain, which serves at the root path.
// While the custom domain is still being provisioned, the deploy workflow sets
// these to the github.io project URL so the preview renders with its assets.
// Once DNS is live, drop the `env:` block from .github/workflows/deploy.yml.
const site = process.env.SITE_URL ?? 'https://www.paulmarinos.com';
const base = process.env.BASE_PATH ?? '/';

// https://astro.build/config
export default defineConfig({
	site,
	base,
	integrations: [
		starlight({
			title: 'Paul Marinos',
			description:
				'Threat intelligence, identity, application security, GRC, penetration testing, AI engineering, detection engineering, cloud security, incident response, and data privacy — and the connective tissue between them.',
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/paulmarinos' },
			],
			customCss: ['./src/styles/custom.css'],
			// Caps the autogenerated sidebar at pillar -> subsection by collapsing a
			// directory whose only visible entry is its own index page back into a
			// plain link. See the file for why Starlight cannot do this itself.
			// Must not live at ./src/middleware.ts — Astro claims that path.
			routeMiddleware: './src/starlightRouteData.ts',
			components: {
				PageSidebar: './src/components/PageSidebar.astro',
				Footer: './src/components/Footer.astro',
				// Not a banner — a global hook for the mobile-nav enhancement.
				Banner: './src/components/Banner.astro',
			},
			plugins: [
				starlightThemeBlack({
					sidebar: {
						// Without this the theme renders each pillar as a static label
						// with its children always expanded — `collapsed: true` below
						// has no effect. With it, each pillar becomes a <details>
						// disclosure that honours `collapsed` and auto-opens the group
						// containing the current page.
						useDropdowns: true,
					},
					docs: {
						// Off by default here: the stock behaviour puts
						// "Open in ChatGPT / Claude / v0 / Scira" buttons on every page.
						showMarkdownActions: false,
					},
				}),
				starlightSiteGraph({
					// Edges come from real links in page content — the "How this
					// connects" sections are already the cross-pillar edge list.
					// Nav, header, footer and the right sidebar are excluded by
					// default, so only editorial links become edges.
					//
					// We render the panels ourselves (src/components/PageSidebar.astro
					// and Footer.astro) so the graph sits *below* the table of contents
					// and still appears on mobile, where the right sidebar is hidden.
					overridePageSidebar: false,
					graphConfig: {
						// Depth 1 already shows the whole graph today: the pillars form
						// a complete mesh, so every pillar is a direct neighbour of every
						// other. Measured identical to depth 2 at the current 11 nodes.
						// It stops being identical once articles land — at 4 articles per
						// pillar, depth 1 shows 18 nodes (94% on screen) against depth 2's
						// 50 (74%). Readers can still raise it with the graph's depth control.
						depth: 1,
						renderArrows: true,
						// The plugin defaults `linkDistance` to 0, so layout is driven
						// only by repulsion and nodes clump with overlapping labels.
						linkDistance: 150,
					},
					sitemapConfig: {
						// The backlinks panel lists inbound pages, and its anchors were
						// being counted as *outbound* edges — invisible while every pillar's
						// inbound and outbound sets are identical, but it would make the
						// arrows meaningless as soon as articles exist. The Related block
						// is deliberately not excluded: those links are meant to be edges.
						ignoreLinksInSelectors: [
							'header',
							'footer',
							'nav',
							'.right-sidebar',
							'.site-title',
							'.slsg-backlinks-panel',
							// theme-black renders the whole sidebar again as a <div
							// class="mobile-nav">, not a <nav>, so the tag-based exclusion
							// above misses it and every page gained an edge to every pillar.
							// Invisible on pillar pages, which already link to all the
							// others; wrong on articles.
							'.mobile-nav',
							// theme-black's Pagination override renders prev/next outside
							// <footer>, so "next page" was becoming a content edge too.
							'.nav-buttons',
						],
						// One colour per pillar, driven by the table above.
						// Globs are written both bare and `**/`-prefixed so they match
						// whether or not a base path is prepended to the node key.
						styleRules: new Map(
							pillars.map(({ dir, color }) => [
								[`${dir}/**`, `**/${dir}/**`],
								{ shapeColor: color },
							]),
						),
						// Tag each page with its pillar so the graph can be filtered.
						// Essays get a tag but no styleRule: the colour slots are
						// exhausted at ten (see the pillars table), and the default
						// node colour marks them as deliberately outside the palette —
						// same treatment as the threads.
						tagRules: Object.fromEntries([
							...pillars.map(({ dir }) => [dir, [`${dir}/**`, `**/${dir}/**`]]),
							['essays', ['essays/**', '**/essays/**']],
						]),
					},
				}),
				// Fails the build on broken internal links. This is what gives
				// `relatedTo` referential integrity — the content schema only checks
				// that at least one entry points outside the article's own pillar, not
				// that the target exists.
				starlightLinksValidator({
					// Internal links are written absolute (`/iam/`). That is only safe
					// because the custom domain serves at base '/' — markdown links are
					// not base-prefixed by Astro, so absolute ones would 404 under a
					// path base. If a path base ever comes back, this has to be revisited
					// along with every prose link.
					//
					// With this true the plugin resolves prose links and rejects any that
					// are relative, which is now the thing we want: relative links were
					// the unvalidated case (skipped when false, rejected for being
					// relative when true), and depth mistakes in them created phantom
					// graph nodes rather than 404ing. `relatedTo` is still enforced
					// separately in src/components/RelatedArticles.astro, because the
					// plugin only sees links written in markdown.
					errorOnRelativeLinks: true,
				}),
			],
			// No `editLink`: this is an authored portfolio, not community docs — the
			// "Edit page" button invites fork/PR edit proposals we don't want. Re-add
			// an `editLink: { baseUrl: '.../edit/main/' }` block to bring it back.
			lastUpdated: true,
			// Only the pillar directories: `essays/` and `threads/` are deliberately
			// absent, surfaced through the homepage, search, the graph and backlinks
			// instead of the navigation.
			sidebar: pillars.map(({ label, dir }) => ({
				label,
				collapsed: true,
				items: [{ autogenerate: { directory: dir } }],
			})),
		}),
	],
});
