/**
 * Caps the autogenerated sidebar at two levels: pillar -> subsection.
 *
 * Third-level articles carry `sidebar: { hidden: true }` in frontmatter, which
 * Starlight filters out in `treeify()` *before* building the tree — so their
 * directory never becomes a sidebar group of its own. What it does not do is
 * collapse the now-pointless wrapper: a subsection that has become a directory
 * (`appsec/api-cloud-native/index.mdx` + hidden children) still renders as a
 * group labelled `api-cloud-native` containing a single link to its own index,
 * because `dirToItem()` turns every directory into a group unconditionally.
 *
 * This rewrites that wrapper back into the plain link it was when the
 * subsection was still a single file, so growing a subsection into a directory
 * is invisible in the navigation. The mobile menu benefits too, and more than
 * the sidebar does: the theme's MobileNav renders only `type === 'link'`
 * children, so an un-flattened group would not appear there at all.
 *
 * The match is deliberately narrow — a group holding exactly one link whose
 * final path segment equals the group's own label, which is the raw directory
 * name for autogenerated groups. That is only ever true of a directory index.
 * A subsection with two or more visible children still renders as a group.
 */
import { defineRouteMiddleware, type StarlightRouteData } from '@astrojs/starlight/route-data';

type SidebarEntry = StarlightRouteData['sidebar'][number];

/** The final path segment of a sidebar link's href, ignoring trailing slashes. */
function lastSegment(href: string): string {
	const path = href.split(/[?#]/)[0] ?? '';
	const parts = path.split('/').filter(Boolean);
	return parts[parts.length - 1] ?? '';
}

function flatten(entries: SidebarEntry[]): SidebarEntry[] {
	return entries.map((entry) => {
		if (entry.type !== 'group') return entry;

		const inner = flatten(entry.entries);
		const only = inner.length === 1 ? inner[0] : undefined;

		if (only && only.type === 'link' && lastSegment(only.href) === entry.label) {
			return only;
		}

		return { ...entry, entries: inner };
	});
}

export const onRequest = defineRouteMiddleware((context) => {
	const route = context.locals.starlightRoute;
	if (!route) return;
	route.sidebar = flatten(route.sidebar);
});
